// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TiendaDeVideojuegosWebApi.Migrations
{
    [DbContext(typeof(TiendaContext))]
    [Migration("20250205072018_CarritoJuegoADDED")]
    partial class CarritoJuegoADDED
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TiendaDeVideojuegosWebApi.Data.Carrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Carritos");
                });

            modelBuilder.Entity("TiendaDeVideojuegosWebApi.Data.Desarrollador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Desarrolladores");
                });

            modelBuilder.Entity("TiendaDeVideojuegosWebApi.Data.Juego", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DesarrolladorId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DesarrolladorId");

                    b.ToTable("Juegos");
                });

            modelBuilder.Entity("TiendaDeVideojuegosWebApi.Data.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TiendaDeVideojuegosWebApi.Models.CarritoJuego", b =>
                {
                    b.Property<int>("CarritoId")
                        .HasColumnType("int");

                    b.Property<int>("JuegoId")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.HasKey("CarritoId", "JuegoId");

                    b.HasIndex("JuegoId");

                    b.ToTable("CarritoJuegos");
                });

            modelBuilder.Entity("TiendaDeVideojuegosWebApi.Data.Carrito", b =>
                {
                    b.HasOne("TiendaDeVideojuegosWebApi.Data.Usuario", "Usuario")
                        .WithOne("Carrito")
                        .HasForeignKey("TiendaDeVideojuegosWebApi.Data.Carrito", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TiendaDeVideojuegosWebApi.Data.Juego", b =>
                {
                    b.HasOne("TiendaDeVideojuegosWebApi.Data.Desarrollador", "Desarrollador")
                        .WithMany("Juegos")
                        .HasForeignKey("DesarrolladorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Desarrollador");
                });

            modelBuilder.Entity("TiendaDeVideojuegosWebApi.Models.CarritoJuego", b =>
                {
                    b.HasOne("TiendaDeVideojuegosWebApi.Data.Carrito", "Carrito")
                        .WithMany("Juegos")
                        .HasForeignKey("CarritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TiendaDeVideojuegosWebApi.Data.Juego", "Juego")
                        .WithMany()
                        .HasForeignKey("JuegoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrito");

                    b.Navigation("Juego");
                });

            modelBuilder.Entity("TiendaDeVideojuegosWebApi.Data.Carrito", b =>
                {
                    b.Navigation("Juegos");
                });

            modelBuilder.Entity("TiendaDeVideojuegosWebApi.Data.Desarrollador", b =>
                {
                    b.Navigation("Juegos");
                });

            modelBuilder.Entity("TiendaDeVideojuegosWebApi.Data.Usuario", b =>
                {
                    b.Navigation("Carrito")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
